### ISSUE TITLE
Establish engineering team processes

### ISSUE THREAD

**Issue by carjug** [18F/OPRE-Unicorn#23]
As an engineering team, we would like to have a shared understanding for how we will collaborate, what our coding standards and processes are, and who fulfills/shares what roles.

**Goals**
Establish how we will work together and decide on what our team standards and processes will be going forward (subject to iteration, as always)

**Tasks**

- [x] Document in `docs/how_we_work.md` agreed upon git/github practices
- [x] Document in `docs/how_we_work.md` coding standards & processes
- ~Document in `docs/how_we_work.md` eng team roles and shared responsibilities~ [moving this one to its own card]

**Comment by alexsoble** [comment]
We moved forward on this today! We held a facilitated exercise to discuss preferences & experiences with git & GitHub flows; coding standards & processes; and divvying up eng work. Notes are in the [running notes doc.](https://docs.google.com/document/d/1ZfdtFVgrXBwxWsH2ur_JtIcy5EslvlZYzqW2rPnZz-k/edit#) 

**Next up:**

- Synthesize the results of our discussion into a v0.1 "Engineering team practices & norms" 
  - A first draft could be in Google Docs but we think this should ultimately go in the GitHub wiki, since this is engineering team documentation but loosely coupled with the code
  - The synthesis could be tackled either in another coworking session, or async by anyone who wants to take a crack at synthesizing, or a mix of both
- Continue work on better defining eng team roles
  - WINFY ("What I Need From You") exercise scheduled for tomorrow 6/15
  - After that — potentially create "role briefs"?

**Comment by alexsoble** [comment]
Translated our document into Markdown; opened a PR (our first into this repo?!) adding this to the GitHub docs: https://github.com/18F/OPRE-MAPS/pull/48. Requested reviews. 

Last week we thought this would go into GitHub wiki, but in coworking today we went with GitHub source control. 

Will move the associated card into "In Review."

**Comment by alexsoble** [comment]
Created a folder for our ADRS (Architecture Decision Records), added the ADR template, and created skeleton ADRs for the Milestone 0 decisions in our Roadmap: https://github.com/18F/OPRE-MAPS/pull/49

**Comment by alexsoble** [comment]
Woohooo! Now that https://github.com/18F/OPRE-MAPS/issues/23 is merged, I think the following tasks are complete to a first-order approximation:

- [x] Document in `docs/how_we_work.md` agreed upon git/github practices
- [x] Document in `docs/how_we_work.md` coding standards & processes

There may be a bit more to do on this remaining task: 

- [ ] Document in `docs/how_we_work.md` eng team roles and shared responsibilities

There's a mention in "Establish overall team processes" https://github.com/18F/OPRE-MAPS/issues/31#issuecomment-865370725 about discussing the idea of implementing a Tech Lead role after July 4. My proposal would be to close out this particular card, and then break out new cards for "Establish engineering team roles" and/or "Evaluate & discuss implementing a Tech Lead role."

**Comment by amymok** [comment]
That sounds good to me!

**Comment by alexsoble** [comment]
@amymok Great, I'll do that! 👍
