### ISSUE TITLE
Decide on a tech stack

### ISSUE THREAD

**Issue by carjug** [18F/OPRE-Unicorn#25]
As engineers, before we can start building, we need to know what tech stack we'll be working in and why.

|    | Alex initial thoughts | Carly | Amy initial thoughts |
|---|------|------|------|
| Frontend | Use Django Template+HTML+USWDS <br/> Use JS as needed, start out with SSR <br/> (server-side rendering) | Depends on what the product needs to do. | Server-rendered HTML, like Django Template, USWDS, Javascript as needed <br/>or<br/>Complete decoupled frontend/backend: HTML/USWDS/React.js/Redux |
| Backend | Django | Django or Flask | Django |
| Database | Postgres | Postgres | Open Source Relational Database: Postgres or MySQL |

**Tasks**

- [x] Determine tech stack for backend and document with a lightweight decision record
- [x] Determine tech stack for frontend and document with a lightweight decision record
- [x] Determine whether or not we need our frontend and our backend to be completely decoupled and document with a lightweight decision record 
- [x] Determine database and document with a lightweight decision record

Related issue #25

**Comment by carjug** [comment]
@amymok @alexsoble I'm pulling this into "In Progress" since Amy mentioned she's started looking into some of the options here already 😄

**Comment by amymok** [comment]
I am adding a few links here, mostly for backend, comparing Django, Flask, and FastAPI:

https://www.section.io/engineering-education/choosing-between-django-flask-and-fastapi/
https://ahmed-nafies.medium.com/why-did-we-choose-fast-api-over-flask-and-django-for-our-restful-micro-services-77589534c036
https://www.reddit.com/r/django/comments/jfuk6d/django_rest_framework_vs_fastapistarlette/
https://codeahoy.com/compare/django-vs-flask.html
https://codeahoy.com/compare/flask-vs-fastapi.html
https://codeahoy.com/compare/django-vs-fastapi.html

**Comment by carjug** [comment]
@amymok @alexsoble Anyone feel particularly strongly about being the "assignee" here? It could be any one of us, IMO.

**Comment by amymok** [comment]
Have your pick!

**Comment by carjug** [comment]
@amymok I'll assign you since you're not ~technically ~ on the board yet :)

**Comment by amymok** [comment]
Add a few more notes, this one is for Django/frontend framework like React.js
https://thenewstack.io/djangos-place-in-a-web-development-world-ruled-by-react/
https://www.quora.com/What-are-the-benefits-of-using-react-js-with-Django

**Comment by amymok** [comment]
Some on separating backend and frontend:
https://www.forbes.com/sites/forbestechcouncil/2018/07/19/seven-reasons-why-a-websites-front-end-and-back-end-should-be-kept-separate/?sh=792b2c1e4fca
https://opensenselabs.com/blog/articles/frontend-backend
https://dev.to/ama/to-separate-or-not-to-separate-frontend-and-backend-3nk9
https://www.quora.com/Why-does-it-make-sense-to-separate-front-end-from-back-end

**Comment by amymok** [comment]
We probably want this space to also include database choice in this issue.  @carjug @alexsoble thoughts?

**Comment by alexsoble** [comment]
@amymok: Sure, let's include DB choice in this! One reference point on the database choice: https://engineering.18f.gov/datastore-selection/. Looks like Postgres is a TTS/18F team default. 

@amymok Do you have any initial opinions about what tech stack we might choose based on the articles you shared?

**Comment by ninamak** [comment]
I am the least knowledgeable person on the team about this stuff, so my thoughts here don't count for very much.  But I can provide a little more context about what I'm envisioning for the product in case it impacts your decisions.

1. I envision that real-time data exploration/manipulation/visualization will be a key aspect of this system, and when I built a similarly-featured tool before, we did find that it required/benefitted from something like React or Angular.  Based on the "Choosing a web architecture" article, that made me think that we were headed towards a single-page app.  Especially this part: "Web applications designed to read from an existing data source — for example, a web application designed to show visualizations or dashboards based on existing datasets."  That is literally the extent of my knowledge, so I'm happy to be informed that server-side rendering would work just as well.

2. The dream would be that this new system could one day communicate with HHS enterprise systems (like their financial management system or grants management system) so that one day no one needs to manually pull data out of one system and enter it into the other.  I have no idea if we'll ever see this day.  But calling it out in case that impacts your thoughts about decoupling.

**Comment by alexsoble** [comment]
Oooooh, thank you for surfacing these @ninamak!

On (1), I would love to dig in more together on the real-time data exploration. Do we envision the system will be receiving new data every second or every minute? Maybe every hour or every day? We should talk about this — I want to understand the needs better. I would also love to see any examples (screenshots or ideally URLs if possible?) of prior tools you have built that you are thinking of as inspiration or examples. 

On (2), that's great to know! Knowing the long-term dream from day 1 is important. That said, to be totally honest, my initial preference on coupling/decoupling would probably be the same when it comes to scoping out V1.0. From what I'm hearing, it sounds like V2.0 or beyond might eventually move in an API-driven direction, which would be wonderful! My gut instinct is to separate out the tech choices required for V1.0 from the tech choices required for V2.0, since the system can evolve over time.

**Comment by ninamak** [comment]
Yeah, can definitely share screen shots, if I can dig them up from my archives :). And "real-time" was the wrong phrase choice.  I meant more "instantaneous interaction" with the data.  We haven't discussed "freshness" of the data yet.

**Comment by alexsoble** [comment]
@ninamak That makes sense! You're 100% right that instantaneous interaction is a good use case for a framework like React or Angular. I would be interested in digging into where those features come into play in our product roadmap & milestones, to help us decide if we need a framework like React from day 1 of development, sometime before 1.0, or sometime after 1.0.

**Comment by amymok** [comment]
@alexsoble What would be the effort like to start with Django as a monolith, and then separate it to both backend with Django, and frontend with React or other frontend framework?

**Comment by amymok** [comment]
My initial thoughts on the backend here:

Backend: Python/Django

Python:
- Ranked as one of the most loved and wanted language in [2020 StackOverflow survey](https://insights.stackoverflow.com/survey/2020#technology-most-loved-dreaded-and-wanted-languages-loved)
- Easy to learn and well structured, which makes it easy to onboard new developers even if they have not used Python before.
- On the rise, which means it is easier to find more developers to continue with the work compare to languages that is losing popularity like Java.

Django seems to fit the need for this CRUD application.
- Features that can be used out of the box for this application without too much development work needed:
  - ORM: since there is a need for a database, each Django project will come with the configuration to a database
  - Authentication/Authorization: There will be some form of authentication/authorization needed, Django already comes with this package, and more if we need to use more specific authentication
  - Admin interface: This will be good for administrator to edit data easily
- Community support: There is also a bigger community for Django, which means there are more developers and supports and additional packages to use.
- Maturity:  Django is a mature product which has been used
- Security: Django does emphasizes on [security](https://docs.djangoproject.com/en/3.2/topics/security/) with different types of built-in protection.
- Although Django seems to be a lot of overhead because it starts with a lot of structures and features from the start, but these features are useful for the application.
- Learning curve, but there are a lot of resources to get familiar
- Structured:  Django need developers to do things in a specific way, i.e. things in certain folder, etc.  This makes it easier for the team to follow the code and make code easier to structure.
Django Rest Framework - We may need to add the Rest Framework if there’s a need for an open API.

Flask seems more fitting for smaller application.
- It is flexible and can stay small, will need to add plugins and extensions for each features, I.e. admin extension, database ORM support like SQLAlchemy.  So it may require more set up and development to do so.  It also may require a bit more intention to structure the code or else the code can become unmanageable.
- Addresses a lot of security concerns, but extensions can add more security risks as a result.
- Community is big as well.

FastAPI is more fitting for smaller and internal tools
- Use mostly for internal tools, like crisis management that needs the speed FastAPI provides
- The packages, support and community are still minimal compare to Django, because it is still a relatively new framework.
- Speed is the highlight for FastAPI but not necessary for this project.  I do not think the scale of the data is needing super high speed. (we are not looking at terabyte or terabyte of data for this application)

**Comment by amymok** [comment]
My Initial thoughts on the frontend and coupling/decoupling front/backend:

This one I am not quite ready to pick a choice yet, here are some questions I have:

- Is there a need to use the application as a service or not, i.e. using most functionality as a web application by itself vs. having an API available for other applications?
- Will the user need a highly interactive interface?
- How likely will the user interface changes that would need swapping out the frontend to something else at some point?
- Is there a lot of async io we need, i.e. page update and reload by itself with update?

**Choice 1: Server-rendered HTML, like Django Template
USWDS
Javascript as needed**

Benefits for choice 1:
- One repository which makes deployment, integration, system testing, maintaining easier
- If there’s no heavy need to have an open API for other services, coupling also makes sense
    - It can still have some small API endpoints for services though
- Similar concept, syntax
- Efficient/effective when everything is in one codebase because the framework is designed to work well together out of the box
- If Django, admin interface is already available, and we don’t need to implement that

Disadvantages for choice 1:
- Less flexible if we want to have highly interactive interface, if Django, template would not be as flexible, and no async.
- If there’s a need to use a more advanced feature rich frontend, it will need to be rearchitect


**_Or_**

**Choice 2: Complete decoupled frontend/backend:
HTML/USWDS/React.js/Redux**

Benefits for choice 2:
- The separation will allow swapping out backend and frontend easily.  If later, there’s a need to use another technology, as long as the interface between the frontend and backend are defined, it would be easier to do so to change one of them.
- Can reach for specific developers that have higher focus on frontend and backend.
- More modular and likely to work in parallel
- Better for highly interactive user interface

Disadvantages for choice 2:
- More potential security concerns when exposing an API
- More integration is needed to ensure frontend works well with backend

**Comment by amymok** [comment]
Database:

My preference would be an open source relational database, either Postgres or MySQL.

Relational database makes sense (compares to noSQL database) for this application because:
- the data is very organized and have high structures
- Data needs to be searched with complex queries
- models do not change too much, they have roughly the same structures all the time
- Data consistency and accuracy is important

**Comment by carjug** [comment]
My initial thoughts on the tech stack

**Overall**

Overall I agree with @alexsoble that we should follow a monorepo pattern for this application so as to avoid the complexity of needing to deploy/maintain two separate services/repositories. I think this will ease maintainability in the long run to have all the code in one place and deployed from one place.

**Front end**

My opinions on where to start with the front end really depend on what our plans for the feature set of MVP will be. I know that we have been thinking about the potential to do some features that would involve interactive data visualization, in which case I'd recommend that we plan to use a JS library that specializes in such a thing such as [Javascript D3](https://github.com/d3/d3). 

I'm not convinced we need a full-fledged single page web app using ReactJS in the beginning, but speaking from prior work experience, it can become kind of crufty and cumbersome to shove React into a formerly SSR frontend if we ever did need it. So that's something I'd really like us to consider.

**Back end**

I concur with the group that Django has a lot of out-of-the-box features that make for ease of development, so I would be happy to use Django. One thing I want to consider is, is it possibly _too much_ and/or _too big_ for what we need? I don't have an opinion, I just want to make sure we don't use a sledgehammer for a pushpin or whatever.

I've used Flask and have found it to be very easy to use with lots of reliable and readable documentation. It does take a bit more work than Django to get a Flask app connected to a database, but it's doable no doubt. It's very lightweight and would suggest this if we go the single page web app route.

**Database**

Finally, I agree with the group about using an OS SQL database, and it is my understanding the Postgres is the 18F default. I am by no means a database expert, but trust my colleagues' opinions here.

**Comment by carjug** [comment]
GIven that all of our remarks are here now, I will move the related ticket into "In Review" now.

**Comment by ninamak** [comment]
Leaving a few additional thoughts/perspectives in case they're helpful to you in making the front-end decisions (and to double-check that i've shared what's in my brain with y'all):

* I'd like us to think about what we think the vendor will mostly be needing to use.  One of our goals is to lay a technical foundation for the vendor, and if they're going to have to swap out the front end to deliver beyond MVP, then that would be less helpful.
* Similarly, my read is that OPRE would generally prefer to not have to change out tech later just to get an MVP slightly sooner.  They value iterating on the feature set, but probably less so on the tech stack.  (Obviously this calculation changes if the time savings implications are significant)
* If getting Unicorn fully up and running becomes the urgent #1 priority outweighing everything else, then the above considerations become less important.

In terms of features that we expect Unicorn to have (with the caveat this is hardly solidified yet):
* Instantaneous interaction with data (e.g., selecting and rearranging columns, filtering, sorting, grouping, collapsing and expanding groups, selecting rows to perform an action on (or to custom filter))
* Exports
* Search
* We do not know how important data visualization is
* Editing multiple rows of data
* Proposing edits to data, allowing review & approval of edits
* Basic data entry
* Bulk uploading data (e.g., a spreadsheet to update data in Unicorn)
* Alerts or notifications
* Workflow visualization and automation (which would require being able to configure the flows)
* Automated emails (which would require being able to create templates, edit, and send)
* Dashboards (e.g., items awaiting action, overdue items, most recently viewed items, etc)
* Scheduled reports/emails
* PDF reports

**Comment by carjug** [comment]
Lol I love that putting # + 1 linked to our first ever card here 😂

**Comment by ninamak** [comment]
D'oh!  Fixed it

**Comment by amymok** [comment]
>Instantaneous interaction with data (e.g., selecting and rearranging columns, filtering, sorting, grouping, collapsing and expanding groups, selecting rows to perform an action on (or to custom filter))

It depends what "Instantaneous interaction" mean here.  Like a lot of user interfaces, require a submit button clicked after certain selection is made, does that mean instantaneous?  Or are we talking about it is important that after selection is made, things will change, no submit button is wanted.

I would expect the former is fine?

**Comment by amymok** [comment]
@alexsoble will work on the ADR for the backend selection.

We will need to have a group discussion with the whole team to understand the features needed for Unicorn before we do a frontend selection.

**Comment by alexsoble** [comment]
Back-end decision ADR ready for review: https://github.com/18F/OPRE-Unicorn/pull/59#issuecomment-873213928

**Comment by ninamak** [comment]
To help further the discussion about front-end frameworks: 
Nina to share some reporting UIs with the team
Nina to send Alex links to demos of MAPS 1.0
Alex to send Sheila links to blog posts referenced above.

**Comment by carjug** [comment]
Coming back to this next week after Alex has become more familiarized with the current MAPS product.

**Comment by ninamak** [comment]
@alexsoble Assigning this one to you so you can let us know when you're ready to pick back up discussion of this (once you get more familiarized with current MAPS).

**Comment by alexsoble** [comment]
@ninamak 👍 👍 Thank you, sounds perfect!

**Comment by alexsoble** [comment]
Merged in our team decision on back-end tech stack for web framework: https://github.com/18F/OPRE-Unicorn/pull/59

We'll turn to the frontend architecture decision next week.

**Comment by alexsoble** [comment]
Talked with the team about frontend choices:

We're going to go with Django server-rendered HTML to start, and add JS incrementally or per-page to power features that will need a lot of interactivity, like the grid view. 

ADR-writing assigned to me!

**Comment by alexsoble** [comment]
Ooooops! Did not mean to close.

But I do have a question... I see the card is in "In Review", what does that mean? The tech stack ADRs have already been reviewed and approved by the eng team and PM. 

Does "In Review" mean we're waiting for a particular meeting or ceremony before we mark "Done"?

**Comment by carjug** [comment]
We can move to "Done" by my view.
