### ISSUE TITLE
Set up for spike on Oracle DB

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#3]
### Goals

- Get things set up to do the spike to determine the structure and content of the Oracle DB

### Tasks

- [x] Verify with vendor that access will be to a server that reflects production DB
- [x] Get access to Oracle DB
- [x] Get the lay of the land (timebox 8-16 hours)
- [x] Refine spike as needed

### Risks

- Vendor only gives us access to an Oracle server that doesn’t reflect production.

### Mitigation
- Remind vendor that Carly is waiting for an answer about this.  Follow up daily until a response is received.  Escalate to Sheila if no response after 1 week

**Comment by ninamak** [comment]
@carjug I'm cleaning up our GH Board and found this card on our old sprint board.  Since this has been part of our Milestone 0, I'm adding it to our board there and marking it as "In Review" so you can determine if it's ready to be closed or if anything additional is needed.

**Comment by carjug** [comment]
Ok, thank you, Nina! I think it can be moved to done given that we got access and Amy has been able to dive deeply into the DB.
