### ISSUE TITLE
Spike: Determine structure and content of Oracle DB

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#4]
### Goals

- Validate the structure of the data to understand what data is in the DB, what the schema is, and inform if we need to change the schema.  
- Determine if there are any triggers (processes running inside the db, either event-based or schedule-based), which will inform the complexity of the migration.  
- Get more familiar with Oracle db, figure out the unknown unknowns, learn by doing to better understand what the data looks like and how to pull it out.

### Tasks

- [ ] Document the schema
- [ ] Document a list of all the triggers based on schedule or events
- [ ] Compile a list of questions we still have
