### ISSUE TITLE
Establish eng team roles

### ISSUE THREAD

**Issue by alexsoble** [18F/OPRE-Unicorn#56]
As an engineering team, we would like to have a shared understanding for who fulfills/shares what roles.

**Notes**

Broke out this card from the larger eng team processes card, #23. 

**Tasks**

+ [x] Evaluate & discuss implementing a tech lead role
+ [x] Evaluate & discuss other eng team roles needed for the project
+ [x] Document our decisions

**Comment by ninamak** [comment]
@alexsoble What are you seeing as the blockers here?  Outages?  Waiting on the work the Eng chapter is doing on this topic?  Something else?

**Comment by alexsoble** [comment]
@ninamak Outages — just channeling what you wrote here! https://github.com/18F/OPRE-MAPS/issues/31#issuecomment-865370725

> This is unlikely to happen this week before people start heading out (and there will be fewer people to coordinate while people are out), so we will likely pick this back up after July 4. Eng may have more guidance for us by that point, too.

We could pick the discussion up after July 4. 

And as you note — eng may have more guidance for us by that point, too!

**Comment by ninamak** [comment]
Got it, thanks!  Was just wondering if anything else had been raised.  So I'm going to remove the tech lead convo from the scope of #31 since it's covered here.

**Comment by ninamak** [comment]
Eng has said they have no more guidance for us.  Mtg to discuss what we want in the Tech Lead role scheduled for Tues 7/13

**Comment by carjug** [comment]
@amy to add things here :) the rest of the engineering team will review/help where needed! yay for formalizing things.

**Comment by amymok** [comment]
During our eng team lead role discussion, we have also identified the engineering work we need to do for this project.  We created a table with the list of engineering work, and the primary person responsible for the work.  A backup person was also identified for each in the case the primary person is unavailable.

We also wanted to point out the work identified with an asterisk (*) are big tasks, and will require significant effort.  We want to be mindful when we assign work for each engineer.

 Engineering Work | Primary | Backup
-- | -- | --
More tech-lead-specific things… <br><br>Keep tabs on the different eng streams and whether they’re flowing smoothly individually and together<br><br>Ensure engs have a good sense of their roles; eng team roles/shape matched to the work that needs doing | AM | ARS
Meet with PM to provide initial perspective on draft milestones, cycles, stories | AM | CJ
Meet with OCIO to represent project, fill out ATO docs* | ARS | AM, CJ
Guide eng team to technical decisions | ARS | AM, CJ
Implementation — back end | CJ | AM
Implementation — front end | ARS | CJ
Implementation — database migration* | AM | CJ
(future/TBD) Train up partner tech lead |   |
