### ISSUE TITLE
Discuss ATO strategy with Sheila

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#60]
### Goals
* Determine when we will begin the OCIO intake process

### Tasks
- [x] [started] Provide Sheila background on 18F's approach to ATOs, within ACF and across agencies
- [x] Identify questions Naomi and Emily may be interested in
- [x] Determine when to brief Naomi and Emily (at next brief out or one-off)

**Comment by ninamak** [comment]
Mtg to discuss with Sheila scheduled for 7/9

**Comment by alexsoble** [comment]
This week:

+ Made a deck about 18F's approach to ATOs, within ACF and across agencies
+ Got great feedback and help from @ryanhofdotgov and @rahearn
+ Started previewing the deck with Sheila and getting feedback

Next up:

+ Go thru rest of the deck with Sheila, likely Monday 7/12
+ Edit and improve the deck next week 
+ Send deck to Naomi ahead of time, maybe 7/19
+ Briefing with Namoi on 7/26

**Comment by alexsoble** [comment]
(Edited the tasks lists a little bit to reflect what we've learned and discussed.)

**Comment by ninamak** [comment]
Flagging here that in talking through the [DB migration test work](https://github.com/18F/OPRE-Unicorn/issues/34#issuecomment-872506593) with @amymok, we think there's about 2-4 weeks of testing we can do before we're blocked by needing to talk to the OCIO about ACF/HHS AWS access.

**Comment by ninamak** [comment]
Convo to be cont'd with Sheila on Tues 7/13

**Comment by alexsoble** [comment]
Discussed and updated deck with Sheila today.

**Comment by alexsoble** [comment]
Sheila would like us to attach the slide deck to the meeting cal invite as a pre-read.
