### ISSUE TITLE
Discuss impact that agreement will have on our strategy and roadmap

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#64]
**Goals**
* Determine whether any changes to our plans are needed to accommodate changes in how funds will be allocated to agreements

**Tasks**
- [x] Nina to stay in sync with Elie and Sheila about options for agreements
- [x] Nina to consult with team on options and impacts
- [x] Meet with Sheila to discuss options
- [x] Understand Naomi's preferences
- [x] Determine if any changes are needed

**Comment by ninamak** [comment]
Mtg scheduled with Sheila 7/9

**Comment by ninamak** [comment]
We have a plan to move forward on agreements with Sheila that Naomi has indicated support for.  That plan will not require us to make any changes to our work (at least not any time soon).
