### ISSUE TITLE
Validate whether AWS DMS works the way we need it to

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#7]
### Goals
- Determine if AWS DMS meets our needs
  - Proposed plan: GT allows our AWS environment to VPC peer into Oracle db. We set up and use AWS DMS (data migration service) to establish a connection between the two dbs and do the migration + translation into the new db.  There may be a need to use AWS SCT (Schema Conversion Tools), if stored procedures, triggers, other schema objects, etc. are used, bc AWS DMS doesn't support migrating these.
https://docs.aws.amazon.com/dms/latest/sbs/chap-rdsoracle2postgresql.html.  Set up auto sync for updates, which requires a continual VPC peering (not one-time).  Then either connect cloud.gov to the new db, or do another db migration into a cloud.gov-provisioned instance of PostGreS.
- Determine if an alternate migration plan would better meet our needs
  - One alternative: There are tools that can be used with dev scripts (e.g., Ora2PG).  We’d have to run the script somewhere to do the migration + translation straight from Oracle to cloud.gov.  This would require more work/labor and would require manual syncs, but could be a solution if AWS DMS doesn't meet our needs or OCIO is unwilling to support VPC peering.

### Tasks

- [ ] Ask in #dev if anyone has done any sort of VPC peering
- [ ] Request that vendor do the VPC peering work
  - Level set how much effort something like this is expected to take
  - Possibly pair
- [ ] Probably set up AWS DMS to go from dev env to dev env
- [ ] Evaluate which migration plan will work better and faster for us, given both the labor and the bureaucracy issues

### Risks
- Requires cooperation from vendor for VPC peering.

**Comment by ninamak** [comment]
Replaced by other cards
