### ISSUE TITLE
Perform heterogeneous migration with sample database (Oracle to PostgreSQL)

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#75]
### Goals
* Test if we can use the AWS DMS to migrate databases, when they're in the same VPC and are of different types (tests schema migration & transformation).

### Tasks
- [ ] Create Postgres DB in TTS Sandbox
- [ ] Migrate schema using schema conversion tools
- [ ] Migrate data using AWS DMS
