### ISSUE TITLE
Determine how we'll do estimation

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#77]
### Goals
* To align as a team on how we'll do estimation for GH issues and milestones so that we can better plan our scope for each cycle and our overall roadmap.

### Tasks

- [x] Determine when and whether we'll use T-shirt sizes or Points to estimate issues and milestones
- [x] If Points, determine whether we'll use a Fibonacci scale (1, 2, 3, 5, 8, 13) or an exponential scale (1, 2, 4, 8, 16, 32)
- [ ] Discuss our interest in measuring velocity and burndown.  
- [ ] If interested, discuss our process for reviewing velocity and burndown.
- [ ] Align on a reference story for a mid-sized issue
- [ ] Document decisions and processes
- [x] Provide Sheila some background info on points and estimation

**Comment by ninamak** [comment]
@carjug @amymok @alexsoble I re-discovered that I'd previously put together a deck on [Estimation](https://docs.google.com/presentation/d/1O3pwzJVbisBqDNu4M-IafzqAXajblFCLsvq_9hHA4cY/edit#slide=id.gb82351d05c_0_472), and it conveniently still accurately describes my thoughts on why estimation is useful and how to do it, including tips/advice based on years of experience with many different teams.

Would love for you to give a look through and then fill in your preferences _for what makes sense for this project_ in the table below (adding additional notes/comments in the comment thread if you want to elaborate).  I've already put in my preferences, but I'm not wedded to them.

| For Sprint Planning | Nina | Alex | Carly | Amy | 
|----------------|-----|------|------|-----|
| Points or T-Shirt Sizes? | Points |  |  |  |
| If Points, Fibonacci or Exponential? | Exp |  |  |  |

I've also put together an [affinity grouping exercise](https://app.mural.co/t/gsa6/m/gsa6/1626278942128/724d701c4385a01cf211eeffdf6e79e679df3347) using stories from Milestone 0.  My thinking is that you can do the exercise async, and if we need to we can use sync time to discuss areas where there's disagreement and align.  We can create/name the buckets once we’ve agreed on what system we’ll use for estimation.

**Comment by alexsoble** [comment]
In issue grooming today we decided to go with points + exponential!

**Comment by alexsoble** [comment]
@amymok You had some good ideas//reference points on what 1, 2, 4, 8, 16, 32 points each map to. When you have a minute, could you leave those reference points here? Thank you!

**Comment by amymok** [comment]
I was mostly talking about the fib version, but probably can translate to the exp version.
1 - Really trivial, like typos, word changes
2 - Easy to change, no need to do additional research, but requires a bit more effort than the trivial 1 task, like need to reword some paragraphs, fixing some easy flake 8 errors
3 - Requires more effort, a medium task, maybe some research on reminding yourself how to do a task, but no unknowns
8 - Requires a lot of effort, there may be 1 unknown to research more about, or the task is really big and requires a lot more effort and thoughts, may want to think about breaking it up into a few smaller tasks
13 - this is too big to even talk about at this point, also can be more than 1 unknowns that need to figure out first.  Need to break it up into smaller tasks

**Comment by alexsoble** [comment]
Thanks @amymok! This is a super helpful frame of reference!

**Comment by ninamak** [comment]
Is there anything left to do with this issue before closing it out @amymok @alexsoble @carjug ?

**Comment by carjug** [comment]
I think it's all good from my perspective.

**Comment by ninamak** [comment]
Next step:

- [ ] Pull out the decisions and framework for point values and document in the How We Work doc
